apiVersion: v2
name: n8n
description: A Helm chart for n8n workflow automation with Redis
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - n8n
  - workflow
  - automation
  - redis
home: https://n8n.io
sources:
  - https://github.com/n8n-io/n8n
maintainers:
  - name: Your Name
    email: your-email@example.com