# Custom values for n8n deployment
# Domain: n8n.lolmeida.com

global:
  timezone: "Europe/Lisbon"

n8n:
  image:
    repository: n8nio/n8n
    tag: "latest"
    pullPolicy: IfNotPresent

  replicaCount: 1

  auth:
    enabled: true
    username: "admin"
    password: "n8n-changeme123"  # Change this!

  config:
    domain: "n8n.lolmeida.com"
    protocol: "https"
    webhookUrl: "https://n8n.lolmeida.com/"
    editorBaseUrl: "https://n8n.lolmeida.com/"

  service:
    type: ClusterIP
    port: 5678

  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: ""

redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent

  replicaCount: 1

  auth:
    password: "redis-changeme123"  # Change this!

  service:
    type: ClusterIP
    port: 6379

  resources:
    limits:
      memory: "256Mi"
      cpu: "250m"
    requests:
      memory: "128Mi"
      cpu: "100m"

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: ""

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent

  replicaCount: 1

  auth:
    database: "n8n"
    username: "n8n"
    password: "postgres-changeme123"  # Change this!

  service:
    type: ClusterIP
    port: 5432

  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: ""

mysql:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

  replicaCount: 1

  auth:
    database: "n8n"
    username: "n8n"
    password: "mysql-changeme123"  # Change this!
    rootPassword: "mysql-root-changeme123"  # Change this!

  service:
    type: ClusterIP
    port: 3306

  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: ""

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: n8n.lolmeida.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: n8n-tls
      hosts:
        - n8n.lolmeida.com

monitoring:
  # Prometheus - Metrics Collection
  prometheus:
    enabled: true
    image:
      repository: prom/prometheus
      tag: "v2.45.0"
      pullPolicy: IfNotPresent
    
    service:
      type: ClusterIP
      port: 9090
    
    retention: "15d"
    
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: ""
  
  # Grafana - Visualization
  grafana:
    enabled: true
    image:
      repository: grafana/grafana
      tag: "10.2.0"
      pullPolicy: IfNotPresent
    
    auth:
      adminUser: "admin"
      adminPassword: "grafana-changeme123"  # Change this!
    
    config:
      rootUrl: "https://grafana.lolmeida.com"
      dashboards:
        defaultHomeDashboardPath: "/var/lib/grafana/dashboards/n8n-overview.json"
    
    service:
      type: ClusterIP
      port: 3000
    
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: ""
  
  # Ingress for external access
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: grafana.lolmeida.com
        paths:
          - path: /
            pathType: Prefix
            service: grafana
      - host: prometheus.lolmeida.com
        paths:
          - path: /
            pathType: Prefix
            service: prometheus
    tls:
      - secretName: monitoring-tls
        hosts:
          - grafana.lolmeida.com
          - prometheus.lolmeida.com

nodeSelector: {}
tolerations: []
affinity: {} 