# Default values for n8n chart
global:
  timezone: "America/Sao_Paulo"
  namespace: "lolmeida"

n8n:
  image:
    repository: n8nio/n8n
    tag: "latest"
    pullPolicy: IfNotPresent

  replicaCount: 1

  auth:
    enabled: true
    username: "admin"
    password: "changeme123"

  config:
    domain: "m8n.lolmeida.com"
    protocol: "https"
    webhookUrl: "https://m8n.lolmeida.com/"
    editorBaseUrl: "https://m8n.lolmeida.com/"

  service:
    type: ClusterIP
    port: 5678

  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: ""

redis:
  enabled: false  # Disabled by default, enable in custom-values.yaml
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent

  replicaCount: 1

  auth:
    password: "changeme123"

  service:
    type: ClusterIP
    port: 6379

  resources:
    limits:
      memory: "256Mi"
      cpu: "250m"
    requests:
      memory: "128Mi"
      cpu: "100m"

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: ""

# MySQL Database Configuration
mysql:
  enabled: false  # Disabled by default, enable in custom-values.yaml
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

  replicaCount: 1

  auth:
    database: "n8n"
    username: "n8n"
    password: "changeme123"
    rootPassword: "changeme123"

  service:
    type: ClusterIP
    port: 3306

  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: ""

# PostgreSQL Database Configuration
postgresql:
  enabled: false  # Disabled by default, enable in custom-values.yaml
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent

  replicaCount: 1

  auth:
    database: "n8n"
    username: "n8n"
    password: "changeme123"

  service:
    type: ClusterIP
    port: 5432

  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: ""

# Monitoring Stack Configuration
monitoring:
  # Prometheus - Metrics Collection
  prometheus:
    enabled: false  # Disabled by default, enable in custom-values.yaml
    image:
      repository: prom/prometheus
      tag: "v2.45.0"
      pullPolicy: IfNotPresent
    
    service:
      type: ClusterIP
      port: 9090
    
    retention: "15d"
    
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: ""
    
    # Flags for auxiliary resources
    createConfigMap: true
    createServiceAccount: true
    createClusterRole: true
  
  # Grafana - Visualization
  grafana:
    enabled: false  # Disabled by default, enable in custom-values.yaml
    image:
      repository: grafana/grafana
      tag: "10.2.0"
      pullPolicy: IfNotPresent
    
    auth:
      adminUser: "admin"
      adminPassword: "changeme123"
    
    config:
      rootUrl: "http://localhost:3000"
    
    service:
      type: ClusterIP
      port: 3000
    
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: ""
    
    # Flags for auxiliary resources
    createConfigMap: true
  
  # Ingress for monitoring external access
  ingress:
    enabled: false  # Disabled by default, enable in custom-values.yaml
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: grafana.example.com
        paths:
          - path: /
            pathType: Prefix
            service: grafana
      - host: prometheus.example.com
        paths:
          - path: /
            pathType: Prefix
            service: prometheus
    tls:
      - secretName: monitoring-tls
        hosts:
          - grafana.example.com
          - prometheus.example.com

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: m8n.lolmeida.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: n8n-tls
      hosts:
        - m8n.lolmeida.com

nodeSelector: {}
tolerations: []
affinity: {}