{{- if and .Values.monitoring.prometheus.enabled (default true .Values.monitoring.prometheus.createClusterRole) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "n8n.fullname" . }}-prometheus
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "n8n.fullname" . }}-prometheus
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "n8n.fullname" . }}-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ include "n8n.fullname" . }}-prometheus
    namespace: {{ .Release.Namespace }}
{{- end }} 