{{- $deploymentConfigs := fromYaml (include "n8n.deploymentConfigs" .) -}}
{{- range $key, $deployment := $deploymentConfigs }}
{{- if $deployment.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" $ }}-{{ $deployment.name }}
  labels:
    {{- include "n8n.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $deployment.component }}
spec:
  replicas: {{ $deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $deployment.component }}
  template:
    metadata:
      labels:
        {{- include "n8n.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $deployment.component }}
    spec:
      {{- if $deployment.serviceAccountName }}
      serviceAccountName: {{ $deployment.serviceAccountName }}
      {{- end }}
      containers:
        - name: {{ $deployment.name }}
          image: "{{ $deployment.image.repository }}:{{ $deployment.image.tag }}"
          imagePullPolicy: {{ $deployment.image.pullPolicy }}
          ports:
            - name: {{ $deployment.port.name }}
              containerPort: {{ $deployment.port.containerPort }}
              protocol: TCP
          {{- if $deployment.command }}
          command:
            {{- range $deployment.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if $deployment.args }}
          args:
            {{- range $deployment.args }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          env:
            {{- range $deployment.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml $deployment.resources | nindent 12 }}
          volumeMounts:
            - name: {{ $deployment.volumeMount.name }}
              mountPath: {{ $deployment.volumeMount.mountPath }}
            {{- if $deployment.extraVolumeMounts }}
            {{- range $deployment.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
          livenessProbe:
            {{- toYaml $deployment.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $deployment.readinessProbe | nindent 12 }}
      volumes:
        - name: {{ $deployment.volumeMount.name }}
          {{- if $deployment.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "n8n.fullname" $ }}-{{ $deployment.name }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if $deployment.extraVolumes }}
        {{- range $deployment.extraVolumes }}
        - name: {{ .name }}
          {{- if .configMap }}
          configMap:
            name: {{ .configMap.name }}
          {{- else if .emptyDir }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}