{{- if .Values.monitoring.grafana.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-grafana
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.monitoring.grafana.service.type }}
  ports:
    - port: {{ .Values.monitoring.grafana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }} 