{{- if .Values.ingress.n8n.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "n8n.fullname" . }}-ingress
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.ingress.n8n.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.n8n.className }}
  ingressClassName: {{ .Values.ingress.n8n.className }}
  {{- end }}
  {{- if .Values.ingress.n8n.tls }}
  tls:
    {{- range .Values.ingress.n8n.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.n8n.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "n8n.fullname" $ }}-n8n
                port:
                  number: {{ $.Values.services.n8n.port }}
          {{- end }}
    {{- end }}
{{- end }}

{{- if .Values.ingress.monitoring.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "n8n.fullname" . }}-monitoring-ingress
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
  {{- with .Values.ingress.monitoring.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.monitoring.className }}
  ingressClassName: {{ .Values.ingress.monitoring.className }}
  {{- end }}
  {{- if .Values.ingress.monitoring.tls }}
  tls:
    {{- range .Values.ingress.monitoring.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.monitoring.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "n8n.fullname" $ }}-{{ .service }}
                port:
                  number: {{ index $.Values.services .service "port" }}
          {{- end }}
    {{- end }}
{{- end }} 