apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-n8n
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: n8n
spec:
  type: {{ .Values.n8n.service.type }}
  ports:
    - port: {{ .Values.n8n.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: n8n