{{- if .Values.monitoring.prometheus.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-prometheus
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.monitoring.prometheus.service.type }}
  ports:
    - port: {{ .Values.monitoring.prometheus.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }} 