apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-secret
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  n8n-auth-username: {{ .Values.n8n.auth.username | b64enc | quote }}
  n8n-auth-password: {{ .Values.n8n.auth.password | b64enc | quote }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.mysql.enabled }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.grafana.enabled }}
  grafana-admin-password: {{ .Values.monitoring.grafana.auth.adminPassword | b64enc | quote }}
  {{- end }}
---
{{/*
  Helper templates
  */}}
  {{- define "n8n.name" -}}
  {{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
  {{- end }}

  {{- define "n8n.fullname" -}}
  {{- if .Values.fullnameOverride }}
  {{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
  {{- else }}
  {{- $name := default .Chart.Name .Values.nameOverride }}
  {{- if contains $name .Release.Name }}
  {{- .Release.Name | trunc 63 | trimSuffix "-" }}
  {{- else }}
  {{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- define "n8n.chart" -}}
  {{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
  {{- end }}

  {{- define "n8n.labels" -}}
helm.sh/chart: {{ include "n8n.chart" . }}
  {{ include "n8n.selectorLabels" . }}
  {{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  {{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- end }}

  {{- define "n8n.selectorLabels" -}}
app.kubernetes.io/name: {{ include "n8n.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
  {{- end }}