apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-secret
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  n8n-auth-username: {{ .Values.n8n.auth.username | b64enc | quote }}
  n8n-auth-password: {{ .Values.n8n.auth.password | b64enc | quote }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.mysql.enabled }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.monitoring.grafana.enabled }}
  grafana-admin-password: {{ .Values.monitoring.grafana.auth.adminPassword | b64enc | quote }}
  {{- end }}