{{- $serviceConfigs := fromYaml (include "n8n.serviceConfigs" .) -}}
{{- range $key, $service := $serviceConfigs }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" $ }}-{{ $service.name }}
  labels:
    {{- include "n8n.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $service.component }}
spec:
  type: {{ $service.type }}
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
      protocol: TCP
      name: {{ $service.targetPort }}
  selector:
    {{- include "n8n.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $service.component }}
{{- end }}
{{- end }}