{{- if and .Values.monitoring.prometheus.enabled (default true .Values.monitoring.prometheus.createServiceAccount) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n.fullname" . }}-prometheus
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
{{- end }} 