apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s.fullname" . }}-secret
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.database.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  DB_URL: {{ .Values.database.url | b64enc | quote }}
  QUARKUS_PROFILE: {{ .Values.quarkus.profile | b64enc | quote }} 